python autograder.py -p --test test_cases0-lecture-6-tree
python autograder.py -p --test test_cases0-small-tree
python autograder.py -p --test test_cases1-1-minmax
python autograder.py -p --test test_cases1-2-minmax
python autograder.py -p --test test_cases1-3-minmax
python autograder.py -p --test test_cases1-4-minmax
python autograder.py -p --test test_cases1-5-minmax
python autograder.py -p --test test_cases1-6-minmax
python autograder.py -p --test test_cases1-7-minmax
python autograder.py -p --test test_cases1-8-minmax
python autograder.py -p --test test_cases2-1a-vary-depth
python autograder.py -p --test test_cases2-1b-vary-depth
python autograder.py -p --test test_cases2-2a-vary-depth
python autograder.py -p --test test_cases2-2b-vary-depth
python autograder.py -p --test test_cases2-3a-vary-depth
python autograder.py -p --test test_cases2-3b-vary-depth
python autograder.py -p --test test_cases2-4a-vary-depth
python autograder.py -p --test test_cases2-4b-vary-depth
python autograder.py -p --test test_cases2-one-ghost-3level
python autograder.py -p --test test_cases3-one-ghost-4level
python autograder.py -p --test test_cases4-two-ghosts-3level
python autograder.py -p --test test_cases5-two-ghosts-4level
python autograder.py -p --test test_cases6-tied-root
python autograder.py -p --test test_cases7-1a-check-depth-one-ghost
python autograder.py -p --test test_cases7-1b-check-depth-one-ghost
python autograder.py -p --test test_cases7-1c-check-depth-one-ghost
python autograder.py -p --test test_cases7-2a-check-depth-two-ghosts
python autograder.py -p --test test_cases7-2b-check-depth-two-ghosts
python autograder.py -p --test test_cases7-2c-check-depth-two-ghosts
python autograder.py -p --test test_cases8-pacman-game
