python autograder.py -p --test test_cases0-lecture-6-tree.solution
python autograder.py -p --test test_cases0-lecture-6-tree.test
python autograder.py -p --test test_cases0-small-tree.solution
python autograder.py -p --test test_cases0-small-tree.test
python autograder.py -p --test test_cases1-1-minmax.solution
python autograder.py -p --test test_cases1-1-minmax.test
python autograder.py -p --test test_cases1-2-minmax.solution
python autograder.py -p --test test_cases1-2-minmax.test
python autograder.py -p --test test_cases1-3-minmax.solution
python autograder.py -p --test test_cases1-3-minmax.test
python autograder.py -p --test test_cases1-4-minmax.solution
python autograder.py -p --test test_cases1-4-minmax.test
python autograder.py -p --test test_cases1-5-minmax.solution
python autograder.py -p --test test_cases1-5-minmax.test
python autograder.py -p --test test_cases1-6-minmax.solution
python autograder.py -p --test test_cases1-6-minmax.test
python autograder.py -p --test test_cases1-7-minmax.solution
python autograder.py -p --test test_cases1-7-minmax.test
python autograder.py -p --test test_cases1-8-minmax.solution
python autograder.py -p --test test_cases1-8-minmax.test
python autograder.py -p --test test_cases2-1a-vary-depth.solution
python autograder.py -p --test test_cases2-1a-vary-depth.test
python autograder.py -p --test test_cases2-1b-vary-depth.solution
python autograder.py -p --test test_cases2-1b-vary-depth.test
python autograder.py -p --test test_cases2-2a-vary-depth.solution
python autograder.py -p --test test_cases2-2a-vary-depth.test
python autograder.py -p --test test_cases2-2b-vary-depth.solution
python autograder.py -p --test test_cases2-2b-vary-depth.test
python autograder.py -p --test test_cases2-3a-vary-depth.solution
python autograder.py -p --test test_cases2-3a-vary-depth.test
python autograder.py -p --test test_cases2-3b-vary-depth.solution
python autograder.py -p --test test_cases2-3b-vary-depth.test
python autograder.py -p --test test_cases2-4a-vary-depth.solution
python autograder.py -p --test test_cases2-4a-vary-depth.test
python autograder.py -p --test test_cases2-4b-vary-depth.solution
python autograder.py -p --test test_cases2-4b-vary-depth.test
python autograder.py -p --test test_cases2-one-ghost-3level.solution
python autograder.py -p --test test_cases2-one-ghost-3level.test
python autograder.py -p --test test_cases3-one-ghost-4level.solution
python autograder.py -p --test test_cases3-one-ghost-4level.test
python autograder.py -p --test test_cases4-two-ghosts-3level.solution
python autograder.py -p --test test_cases4-two-ghosts-3level.test
python autograder.py -p --test test_cases5-two-ghosts-4level.solution
python autograder.py -p --test test_cases5-two-ghosts-4level.test
python autograder.py -p --test test_cases6-tied-root.solution
python autograder.py -p --test test_cases6-tied-root.test
python autograder.py -p --test test_cases7-1a-check-depth-one-ghost.solution
python autograder.py -p --test test_cases7-1a-check-depth-one-ghost.test
python autograder.py -p --test test_cases7-1b-check-depth-one-ghost.solution
python autograder.py -p --test test_cases7-1b-check-depth-one-ghost.test
python autograder.py -p --test test_cases7-1c-check-depth-one-ghost.solution
python autograder.py -p --test test_cases7-1c-check-depth-one-ghost.test
python autograder.py -p --test test_cases7-2a-check-depth-two-ghosts.solution
python autograder.py -p --test test_cases7-2a-check-depth-two-ghosts.test
python autograder.py -p --test test_cases7-2b-check-depth-two-ghosts.solution
python autograder.py -p --test test_cases7-2b-check-depth-two-ghosts.test
python autograder.py -p --test test_cases7-2c-check-depth-two-ghosts.solution
python autograder.py -p --test test_cases7-2c-check-depth-two-ghosts.test
python autograder.py -p --test test_cases8-pacman-game.solution
python autograder.py -p --test test_cases8-pacman-game.test

