0-expectimax1.solution
0-expectimax1.test
1-expectimax2.solution
1-expectimax2.test
2-one-ghost-3level.solution
2-one-ghost-3level.test
3-one-ghost-4level.solution
3-one-ghost-4level.test
4-two-ghosts-3level.solution
4-two-ghosts-3level.test
5-two-ghosts-4level.solution
5-two-ghosts-4level.test
6-1a-check-depth-one-ghost.solution
6-1a-check-depth-one-ghost.test
6-1b-check-depth-one-ghost.solution
6-1b-check-depth-one-ghost.test
6-1c-check-depth-one-ghost.solution
6-1c-check-depth-one-ghost.test
6-2a-check-depth-two-ghosts.solution
6-2a-check-depth-two-ghosts.test
6-2b-check-depth-two-ghosts.solution
6-2b-check-depth-two-ghosts.test
6-2c-check-depth-two-ghosts.solution
6-2c-check-depth-two-ghosts.test
7-pacman-game.solution
7-pacman-game.test
CONFIG
q4testerprior.sh
